### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by alesapin** [iden-alex/investment_app#1]
### Сборка
1. Не знаю какой репозиторий pip'а надо подключать чтобы там была версия пакета с dev в имени (я про `kivymd==0.104.2.dev0`). Выбрал самую последнюю которая есть в нормальном репозитории (`0.104.1`). Программа запустилась и нажав "Начать игру" всё упало так:
```
[WARNING] [MTD         ] Unable to open device "/dev/input/event16". Please ensure you have the appropriate permissions.
[WARNING] [MTD         ] Unable to open device "/dev/input/event12". Please ensure you have the appropriate permissions.
[INFO   ] [Base        ] Leaving application in progress...
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/dist-packages/kivy/lang/builder.py", line 705, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 542, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 533, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 1253, in kivy.properties.OptionProperty.check
 ValueError: TableRecycleGridLayout.orientation is set to an invalid option 'vertical'. Must be one of: ['lr-tb', 'tb-lr', 'rl-tb', 'tb-rl', 'lr-bt', 'bt-lr', 'rl-bt', 'bt-rl']
 
 During handling of the above exception, another exception occurred:
 
 Traceback (most recent call last):
   File "main.py", line 47, in <module>
     InvestmentFundApp().run()   
   File "/usr/local/lib/python3.8/dist-packages/kivy/app.py", line 950, in run
     runTouchApp()
   File "/usr/local/lib/python3.8/dist-packages/kivy/base.py", line 582, in runTouchApp
     EventLoop.mainloop()
   File "/usr/local/lib/python3.8/dist-packages/kivy/base.py", line 347, in mainloop
     self.idle()
   File "/usr/local/lib/python3.8/dist-packages/kivy/base.py", line 391, in idle
     self.dispatch_input()
   File "/usr/local/lib/python3.8/dist-packages/kivy/base.py", line 342, in dispatch_input
     post_dispatch_input(*pop(0))
   File "/usr/local/lib/python3.8/dist-packages/kivy/base.py", line 248, in post_dispatch_input
     listener.dispatch('on_motion', etype, me)
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/usr/local/lib/python3.8/dist-packages/kivy/core/window/__init__.py", line 1412, in on_motion
     self.dispatch('on_touch_down', me)
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/usr/local/lib/python3.8/dist-packages/kivy/core/window/__init__.py", line 1428, in on_touch_down
     if w.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/usr/local/lib/python3.8/dist-packages/kivy/uix/screenmanager.py", line 1198, in on_touch_down
     return super(ScreenManager, self).on_touch_down(touch)
   File "/usr/local/lib/python3.8/dist-packages/kivy/uix/widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/usr/local/lib/python3.8/dist-packages/kivy/uix/relativelayout.py", line 297, in on_touch_down
     ret = super(RelativeLayout, self).on_touch_down(touch)
   File "/usr/local/lib/python3.8/dist-packages/kivy/uix/widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/usr/local/lib/python3.8/dist-packages/kivy/uix/widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/usr/local/lib/python3.8/dist-packages/kivy/uix/widget.py", line 545, in on_touch_down
     if child.dispatch('on_touch_down', touch):
   File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
   File "/usr/local/lib/python3.8/dist-packages/kivy/uix/behaviors/button.py", line 151, in on_touch_down
     self.dispatch('on_press')
   File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
   File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
   File "kivy/_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
   File "/usr/local/lib/python3.8/dist-packages/kivy/lang/builder.py", line 57, in custom_callback
     exec(__kvlang__.co_value, idmap)
   File "/home/alesap/code/python/investment_app/graphic.kv", line 95, in <module>
     root.start_model()
   File "/home/alesap/code/python/investment_app/GUI/start_window.py", line 51, in start_model
     cur_model.start()
   File "/home/alesap/code/python/investment_app/classes/model_class.py", line 31, in start
     self.screen_manager.screen2.init_model(self)
   File "/home/alesap/code/python/investment_app/GUI/main_window.py", line 19, in init_model
     self.update_screen()
   File "/home/alesap/code/python/investment_app/GUI/main_window.py", line 68, in update_screen
     self.set_table_assets()
   File "/home/alesap/code/python/investment_app/GUI/main_window.py", line 106, in set_table_assets
     self.table_asset = MDDataTable(pos_hint={'center_x': 0.5, 'center_y': 0.5},
   File "/usr/local/lib/python3.8/dist-packages/kivymd/uix/datatables.py", line 927, in __init__
     self.table_data = TableData(
   File "/usr/local/lib/python3.8/dist-packages/kivymd/uix/datatables.py", line 488, in __init__
     super().__init__(**kwargs)
   File "/usr/local/lib/python3.8/dist-packages/kivy/uix/recycleview/__init__.py", line 409, in __init__
     super(RecycleView, self).__init__(**kwargs)
   File "/usr/local/lib/python3.8/dist-packages/kivy/uix/recycleview/__init__.py", line 201, in __init__
     super(RecycleViewBehavior, self).__init__(**kwargs)
   File "/usr/local/lib/python3.8/dist-packages/kivy/uix/scrollview.py", line 539, in __init__
     super(ScrollView, self).__init__(**kwargs)
   File "/usr/local/lib/python3.8/dist-packages/kivy/uix/widget.py", line 359, in __init__
     self.apply_class_lang_rules(
   File "/usr/local/lib/python3.8/dist-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
     Builder.apply(
   File "/usr/local/lib/python3.8/dist-packages/kivy/lang/builder.py", line 541, in apply
     self._apply_rule(
   File "/usr/local/lib/python3.8/dist-packages/kivy/lang/builder.py", line 710, in _apply_rule
     raise BuilderException(rule.ctx, rule.line,
 kivy.lang.builder.BuilderException: Parser: File "<inline>", line 113:
 ...
     111:        height: self.minimum_height
     112:        width: self.minimum_width
 >>  113:        orientation: "vertical"
     114:        multiselect: True
     115:        touch_multiselect: True
 ...
 ValueError: TableRecycleGridLayout.orientation is set to an invalid option 'vertical'. Must be one of: ['lr-tb', 'tb-lr', 'rl-tb', 'tb-rl', 'lr-bt', 'bt-lr', 'rl-bt', 'bt-rl']
   File "/usr/local/lib/python3.8/dist-packages/kivy/lang/builder.py", line 705, in _apply_rule
     setattr(widget_set, key, value)
   File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
   File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
   File "kivy/properties.pyx", line 542, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 533, in kivy.properties.Property.set
   File "kivy/properties.pyx", line 1253, in kivy.properties.OptionProperty.check
```
Таким образом, посмотреть как это работает мне не удалось. Никогда не слышал о библиотеке `kivy`, но судя по ошибке в файле `.pyx` это какие-то биндинги к чему-то. Чтобы нарисовать пару окошек правда нужно было так сложно? Посчитать сумму элементов массива без `numpy` тоже видимо нетривиальная задача.

### По коду

1. Переопределять занятые имена в языке плохая идея (https://github.com/iden-alex/investment_app/blob/main/classes/fund_class.py#L90, https://github.com/iden-alex/investment_app/blob/main/classes/market_class.py#L181, https://github.com/iden-alex/investment_app/blob/main/classes/market_class.py#L228
2. Что-то страшное случилось с отступами в этих файлах https://github.com/iden-alex/investment_app/blob/main/classes/model_class.py#L9-L20, https://github.com/iden-alex/investment_app/blob/main/GUI/main_window.py#L12-L22, https://github.com/iden-alex/investment_app/blob/main/GUI/start_window.py#L10-L53
3. Это что https://github.com/iden-alex/investment_app/blob/main/GUI/main_window.py#L186-L197?
4. Больше похоже на сеттеры или апдейтеры, чем на геттеры https://github.com/iden-alex/investment_app/blob/main/classes/fund_class.py#L100-L112
5. Странно, что актив знает свое количество в фонде https://github.com/iden-alex/investment_app/blob/main/classes/market_class.py#L184. Вроде бы логично, чтобы про это знал фонд?
6. Кстати фонд почему-то всяки избегает хранения активов у себя. Т.е. это довольно странно, что имея объект класса фонд мы не можем узнать сколько и каких активов у него есть. Вся эта информация хранится в классе рынок. Можно представить ситуацию, когда понадобиться обощить программу для нескольких фондов. Придётся всё переделывать или ещё больше нагружать рынок. Я бы унес всю логику по контролю за активами фонда собственно в фонд. В рынке бы я оставил только типы активов и изменения их цен/ставок.
7. Как человек читающий код должен понять, что здесь происходит https://github.com/iden-alex/investment_app/blob/main/classes/model_class.py#L31-L33? Особенно странно, потому что в остальных местах имена, в основном, адекватные.
8. Меня смущают округления в куче мест. Причем где-то это честный `round`, а где-то просто `int`. Возможно так по заданию, но наверное стоит написать комментарий про это.

**Comment by iden-alex** [comment]
Спасибо за ревью кода.
1) По поводу сборки. Необходима конкретна эта версия, так как в прошлых возникает данная ошибка при запуске(непонятно почему, авторы библиотеки при возникновении такой проблемы посоветовали работать с последней версией). Когда начинал писать, выбрал одну из самых популярных библиотек для графики на python - kivy. В последствии понял, что можно было выбрать фреймворк попроще, к тому же у kivyMD некоторые неоптимизации с виджетом "Таблица".

По поводу установки конкретной версии, у меня проблем не было с установкой через pip, также есть способ установки с клонированием их репозитория https://github.com/kivymd/KivyMD и запуском "pip ."  Опишу это в репозитории.

2) По поводу логики хранения активов ответил в письме

**Comment by iden-alex** [comment]
Исправил замечания по поводу кода и сборки в соотв-их коммитах

> ### Сборка
> 1. Не знаю какой репозиторий pip'а надо подключать чтобы там была версия пакета с dev в имени (я про `kivymd==0.104.2.dev0`). Выбрал самую последнюю которая есть в нормальном репозитории (`0.104.1`). Программа запустилась и нажав "Начать игру" всё упало так:
> 
> ```
> [WARNING] [MTD         ] Unable to open device "/dev/input/event16". Please ensure you have the appropriate permissions.
> [WARNING] [MTD         ] Unable to open device "/dev/input/event12". Please ensure you have the appropriate permissions.
> [INFO   ] [Base        ] Leaving application in progress...
>  Traceback (most recent call last):
>    File "/usr/local/lib/python3.8/dist-packages/kivy/lang/builder.py", line 705, in _apply_rule
>      setattr(widget_set, key, value)
>    File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
>    File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
>    File "kivy/properties.pyx", line 542, in kivy.properties.Property.set
>    File "kivy/properties.pyx", line 533, in kivy.properties.Property.set
>    File "kivy/properties.pyx", line 1253, in kivy.properties.OptionProperty.check
>  ValueError: TableRecycleGridLayout.orientation is set to an invalid option 'vertical'. Must be one of: ['lr-tb', 'tb-lr', 'rl-tb', 'tb-rl', 'lr-bt', 'bt-lr', 'rl-bt', 'bt-rl']
>  
>  During handling of the above exception, another exception occurred:
>  
>  Traceback (most recent call last):
>    File "main.py", line 47, in <module>
>      InvestmentFundApp().run()   
>    File "/usr/local/lib/python3.8/dist-packages/kivy/app.py", line 950, in run
>      runTouchApp()
>    File "/usr/local/lib/python3.8/dist-packages/kivy/base.py", line 582, in runTouchApp
>      EventLoop.mainloop()
>    File "/usr/local/lib/python3.8/dist-packages/kivy/base.py", line 347, in mainloop
>      self.idle()
>    File "/usr/local/lib/python3.8/dist-packages/kivy/base.py", line 391, in idle
>      self.dispatch_input()
>    File "/usr/local/lib/python3.8/dist-packages/kivy/base.py", line 342, in dispatch_input
>      post_dispatch_input(*pop(0))
>    File "/usr/local/lib/python3.8/dist-packages/kivy/base.py", line 248, in post_dispatch_input
>      listener.dispatch('on_motion', etype, me)
>    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
>    File "/usr/local/lib/python3.8/dist-packages/kivy/core/window/__init__.py", line 1412, in on_motion
>      self.dispatch('on_touch_down', me)
>    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
>    File "/usr/local/lib/python3.8/dist-packages/kivy/core/window/__init__.py", line 1428, in on_touch_down
>      if w.dispatch('on_touch_down', touch):
>    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
>    File "/usr/local/lib/python3.8/dist-packages/kivy/uix/screenmanager.py", line 1198, in on_touch_down
>      return super(ScreenManager, self).on_touch_down(touch)
>    File "/usr/local/lib/python3.8/dist-packages/kivy/uix/widget.py", line 545, in on_touch_down
>      if child.dispatch('on_touch_down', touch):
>    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
>    File "/usr/local/lib/python3.8/dist-packages/kivy/uix/relativelayout.py", line 297, in on_touch_down
>      ret = super(RelativeLayout, self).on_touch_down(touch)
>    File "/usr/local/lib/python3.8/dist-packages/kivy/uix/widget.py", line 545, in on_touch_down
>      if child.dispatch('on_touch_down', touch):
>    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
>    File "/usr/local/lib/python3.8/dist-packages/kivy/uix/widget.py", line 545, in on_touch_down
>      if child.dispatch('on_touch_down', touch):
>    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
>    File "/usr/local/lib/python3.8/dist-packages/kivy/uix/widget.py", line 545, in on_touch_down
>      if child.dispatch('on_touch_down', touch):
>    File "kivy/_event.pyx", line 709, in kivy._event.EventDispatcher.dispatch
>    File "/usr/local/lib/python3.8/dist-packages/kivy/uix/behaviors/button.py", line 151, in on_touch_down
>      self.dispatch('on_press')
>    File "kivy/_event.pyx", line 705, in kivy._event.EventDispatcher.dispatch
>    File "kivy/_event.pyx", line 1248, in kivy._event.EventObservers.dispatch
>    File "kivy/_event.pyx", line 1132, in kivy._event.EventObservers._dispatch
>    File "/usr/local/lib/python3.8/dist-packages/kivy/lang/builder.py", line 57, in custom_callback
>      exec(__kvlang__.co_value, idmap)
>    File "/home/alesap/code/python/investment_app/graphic.kv", line 95, in <module>
>      root.start_model()
>    File "/home/alesap/code/python/investment_app/GUI/start_window.py", line 51, in start_model
>      cur_model.start()
>    File "/home/alesap/code/python/investment_app/classes/model_class.py", line 31, in start
>      self.screen_manager.screen2.init_model(self)
>    File "/home/alesap/code/python/investment_app/GUI/main_window.py", line 19, in init_model
>      self.update_screen()
>    File "/home/alesap/code/python/investment_app/GUI/main_window.py", line 68, in update_screen
>      self.set_table_assets()
>    File "/home/alesap/code/python/investment_app/GUI/main_window.py", line 106, in set_table_assets
>      self.table_asset = MDDataTable(pos_hint={'center_x': 0.5, 'center_y': 0.5},
>    File "/usr/local/lib/python3.8/dist-packages/kivymd/uix/datatables.py", line 927, in __init__
>      self.table_data = TableData(
>    File "/usr/local/lib/python3.8/dist-packages/kivymd/uix/datatables.py", line 488, in __init__
>      super().__init__(**kwargs)
>    File "/usr/local/lib/python3.8/dist-packages/kivy/uix/recycleview/__init__.py", line 409, in __init__
>      super(RecycleView, self).__init__(**kwargs)
>    File "/usr/local/lib/python3.8/dist-packages/kivy/uix/recycleview/__init__.py", line 201, in __init__
>      super(RecycleViewBehavior, self).__init__(**kwargs)
>    File "/usr/local/lib/python3.8/dist-packages/kivy/uix/scrollview.py", line 539, in __init__
>      super(ScrollView, self).__init__(**kwargs)
>    File "/usr/local/lib/python3.8/dist-packages/kivy/uix/widget.py", line 359, in __init__
>      self.apply_class_lang_rules(
>    File "/usr/local/lib/python3.8/dist-packages/kivy/uix/widget.py", line 463, in apply_class_lang_rules
>      Builder.apply(
>    File "/usr/local/lib/python3.8/dist-packages/kivy/lang/builder.py", line 541, in apply
>      self._apply_rule(
>    File "/usr/local/lib/python3.8/dist-packages/kivy/lang/builder.py", line 710, in _apply_rule
>      raise BuilderException(rule.ctx, rule.line,
>  kivy.lang.builder.BuilderException: Parser: File "<inline>", line 113:
>  ...
>      111:        height: self.minimum_height
>      112:        width: self.minimum_width
>  >>  113:        orientation: "vertical"
>      114:        multiselect: True
>      115:        touch_multiselect: True
>  ...
>  ValueError: TableRecycleGridLayout.orientation is set to an invalid option 'vertical'. Must be one of: ['lr-tb', 'tb-lr', 'rl-tb', 'tb-rl', 'lr-bt', 'bt-lr', 'rl-bt', 'bt-rl']
>    File "/usr/local/lib/python3.8/dist-packages/kivy/lang/builder.py", line 705, in _apply_rule
>      setattr(widget_set, key, value)
>    File "kivy/weakproxy.pyx", line 35, in kivy.weakproxy.WeakProxy.__setattr__
>    File "kivy/properties.pyx", line 498, in kivy.properties.Property.__set__
>    File "kivy/properties.pyx", line 542, in kivy.properties.Property.set
>    File "kivy/properties.pyx", line 533, in kivy.properties.Property.set
>    File "kivy/properties.pyx", line 1253, in kivy.properties.OptionProperty.check
> ```
> 
> Таким образом, посмотреть как это работает мне не удалось. Никогда не слышал о библиотеке `kivy`, но судя по ошибке в файле `.pyx` это какие-то биндинги к чему-то. Чтобы нарисовать пару окошек правда нужно было так сложно? Посчитать сумму элементов массива без `numpy` тоже видимо нетривиальная задача.
> 
> ### По коду
> 1. Переопределять занятые имена в языке плохая идея (https://github.com/iden-alex/investment_app/blob/main/classes/fund_class.py#L90, https://github.com/iden-alex/investment_app/blob/main/classes/market_class.py#L181, https://github.com/iden-alex/investment_app/blob/main/classes/market_class.py#L228
> 2. Что-то страшное случилось с отступами в этих файлах https://github.com/iden-alex/investment_app/blob/main/classes/model_class.py#L9-L20, https://github.com/iden-alex/investment_app/blob/main/GUI/main_window.py#L12-L22, https://github.com/iden-alex/investment_app/blob/main/GUI/start_window.py#L10-L53
> 3. Это что https://github.com/iden-alex/investment_app/blob/main/GUI/main_window.py#L186-L197?
> 4. Больше похоже на сеттеры или апдейтеры, чем на геттеры https://github.com/iden-alex/investment_app/blob/main/classes/fund_class.py#L100-L112
> 5. Странно, что актив знает свое количество в фонде https://github.com/iden-alex/investment_app/blob/main/classes/market_class.py#L184. Вроде бы логично, чтобы про это знал фонд?
> 6. Кстати фонд почему-то всяки избегает хранения активов у себя. Т.е. это довольно странно, что имея объект класса фонд мы не можем узнать сколько и каких активов у него есть. Вся эта информация хранится в классе рынок. Можно представить ситуацию, когда понадобиться обощить программу для нескольких фондов. Придётся всё переделывать или ещё больше нагружать рынок. Я бы унес всю логику по контролю за активами фонда собственно в фонд. В рынке бы я оставил только типы активов и изменения их цен/ставок.
> 7. Как человек читающий код должен понять, что здесь происходит https://github.com/iden-alex/investment_app/blob/main/classes/model_class.py#L31-L33? Особенно странно, потому что в остальных местах имена, в основном, адекватные.
> 8. Меня смущают округления в куче мест. Причем где-то это честный `round`, а где-то просто `int`. Возможно так по заданию, но наверное стоит написать комментарий про это.
